# syntax=docker/dockerfile:1

FROM nixos/nix:2.24.11 AS builder

WORKDIR /build

COPY . .

RUN nix --option filter-syscalls false \
    --extra-experimental-features "nix-command flakes" \
    build --no-link --print-out-paths .#__PACKAGE__

FROM scratch

COPY --from=builder "${RESOLVED_RESULT:-/build/result/bin/__BINARY__}" /__BINARY__

ENTRYPOINT ["/__BINARY__"]
